#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="restic-check{{CHECK_NUMBER}}-scheduler"
check_container_initialized
check_service_initialized init 20-restic
check_service_initialized restic-initialize_repository
source /assets/functions/20-restic
source /assets/defaults/20-restic

setup_container_mode
bootstrap_variables upgrade CHECK

if [[ "${MODE,,}" =~ "standalone" ]] || [ "${1,,}" = "manual" ] || [ "${1,,}" = "now" ]; then
    print_debug "Detected Manual Mode"
    persist=false
    CHECK{{CHECK_NUMBER}}_BEGIN=+0
else
    sleep {{CHECK_NUMBER}}
    if [ -z "${CHECK{{CHECK_NUMBER}}_INTERVAL}" ] ; then
        print_error "No Environment variable for CHECK{{CHECK_NUMBER}}_INTERVAL set! Please set a value. Halting Check Number {{CHECK_NUMBER}}."
        s6-svc -d /var/run/s6/legacy-services/restic-check{{CHECK_NUMBER}}
        exit 1
    fi

    current_time=$(date +"%s")
    today=$(date +"%Y%m%d")

    if [[ $CHECK{{CHECK_NUMBER}}_BEGIN =~ ^\+(.*)$ ]]; then
        waittime=$(( ${BASH_REMATCH[1]} * 60 ))
        target_time=$(($current_time + $waittime))
    else
        target_time=$(date --date="${today} ${CHECK{{CHECK_NUMBER}}_BEGIN}" +"%s")
        if [[ "$target_time" < "$current_time" ]]; then
            target_time=$(($target_time + 24*60*60))
        fi
        waittime=$(($target_time - $current_time))
    fi
    print_debug "Wait Time: ${waittime} Target time: ${target_time} Current Time: ${current_time}"
    print_info "Next Check at $(date -d @${target_time} +"%Y-%m-%d %T %Z")"
    silent sleep $waittime
fi

while true; do
    bootstrap_variables check_init {{CHECK_NUMBER}}
    hour_minute=$(date +%H%M)
    if [ -n "${check_job_blackout_start}" ] && [ -n "${check_job_blackout_finish}" ] ; then
        if [[ "${hour_minute}" > "${check_job_blackout_start}" ]] && [[ "${hour_minute}" < "${check_job_blackout_finish}" ]] ; then
            blackout=true
        else
            blackout=false
        fi
    fi
    if var_true "${blackout}" ; then
        print_notice "Detected Blackout Period - Not performing check operations"
    else
        check_start_time=$(date +"%s")
        print_debug "Repository Check {{CHECK_NUMBER}} routines started time: $(date +'%Y-%m-%d %T %Z')"
        repository check {{CHECK_NUMBER}}
        repository unlock "CHECK {{CHECK_NUMBER}}"
        check_finish_time=$(date +"%s")
        check_total_time=$(echo $((check_finish_time-check_start_time)))
        PROCESS_NAME="restic-check{{CHECK_NUMBER}}-scheduler"
        if [ -z "${exitcode_check}" ] ; then exitcode_check="0" ; fi
        print_info "Repository check {{CHECK_NUMBER}} routines finish time: $(date -d @${check_finish_time} +"%Y-%m-%d %T %Z") with exit code ${exitcode_check}"
        print_notice "Repository check {{CHECK_NUMBER}} routines time taken: $(echo ${check_total_time} | awk '{printf "Hours: %d Minutes: %02d Seconds: %02d", $1/3600, ($1/60)%60, $1%60}')"
    fi

    if var_false "${persist}" ; then
        print_debug "Exiting due to manual mode"
        exit ${exitcode_check};
    else
        if var_true "${stop_scheduler_check}" ; then
            print_error "Stopping check_scheduler due to detected errors. Fix and restart container."
            s6-svc -d /var/run/s6/legacy-services/restic-check{{CHECK_NUMBER}}
        else
            print_notice "Sleeping for another $(($CHECK{{CHECK_NUMBER}}_INTERVAL*60-check_total_time)) seconds. Waking up at $(date -d@"$(( $(date +%s)+$(($CHECK{{CHECK_NUMBER}}_INTERVAL*60-check_total_time))))" +"%Y-%m-%d %T %Z") "
            silent sleep $(($CHECK{{CHECK_NUMBER}}_INTERVAL*60-check_total_time))
        fi
    fi
done