#!/command/with-contenv bash

source /assets/functions/00-container
check_container_initialized
check_service_initialized init 10-restic
source /assets/functions/10-restic
source /assets/defaults/10-restic
PROCESS_NAME="restic-prune-scheduler"

setup_container_mode
if [ -n "${RESTIC_PASSWORD}" ] && [ -z "${REPOSITORY_PASS}" ]  ; then export REPOSITORY_PASS="${RESTIC_PASSWORD}" ; fi
if [ -z "${REPOSITORY_PASS}" ] ; then
    print_error "No REPOSITORY_PASS environment variable set. Halting.."
    s6-svc -d /var/run/s6/legacy-services/restic-prune
    exit 1
fi
export RESTIC_PASSWORD=${REPOSITORY_PASS}

if [[ "${MODE,,}" =~ "standalone" ]] || [ "${1,,}" = "manual" ] || [ "${1,,}" = "now" ]; then
    print_debug "Detected Manual Mode"
    persist=false
    PRUNE_BEGIN=+0
else
    current_time=$(date +"%s")
    today=$(date +"%Y%m%d")

    if [[ $PRUNE_BEGIN =~ ^\+(.*)$ ]]; then
        waittime=$(( ${BASH_REMATCH[1]} * 60 ))
        target_time=$(($current_time + $waittime))
    else
        target_time=$(date --date="${today} ${PRUNE_BEGIN}" +"%s")
        if [[ "$target_time" < "$current_time" ]]; then
            target_time=$(($target_time + 24*60*60))
        fi
        waittime=$(($target_time - $current_time))
    fi
    print_debug "Wait Time: ${waittime} Target time: ${target_time} Current Time: ${current_time}"
    print_info "Next Prune at $(date -d @${target_time} +"%Y-%m-%d %T %Z")"
    sleep $waittime
fi

while true; do
    prune_start_time=$(date +"%s")
    print_debug "Repository Prune routines started time: $(date +'%Y-%m-%d %T %Z')"
    pre_prune
    prune_repo
    prune_errors
    prune_finish_time=$(date +"%s")
    prune_total_time=$(echo $((prune_finish_time-prune_start_time)))
    post_prune
    if [ -z "${exitcode_prune}" ] ; then exitcode_prune="0" ; fi
    print_info "Repository prune routines finish time: $(date -d @${prune_finish_time} +"%Y-%m-%d %T %Z") with exit code ${exitcode_prune}"
    print_notice "Repository prune routines time taken: $(echo ${prune_total_time} | awk '{printf "Hours: %d Minutes: %02d Seconds: %02d", $1/3600, ($1/60)%60, $1%60}')"

    if var_false "${persist}" ; then
        print_debug "Exiting due to manual mode"
        exit ${exitcode_prune};
    else
        if var_true "${stop_scheduler_prune}" ; then
            print_error "Stopping prune_scheduler due to detected errors. Fix and restart container."
            s6-svc -d /var/run/s6/legacy-services/restic-prune
        else
            print_notice "Sleeping for another $(($PRUNE_INTERVAL*60-prune_total_time)) seconds. Waking up at $(date -d@"$(( $(date +%s)+$(($PRUNE_INTERVAL*60-prune_total_time))))" +"%Y-%m-%d %T %Z") "
            sleep $(($PRUNE_INTERVAL*60-prune_total_time))
        fi
    fi
done
